# -*- coding: utf-8 -*-
"""
eps_r sweep of one fixed patch geometry (Part K8, guide 9.3)

Simulates the eps_r 4.4 design (the one to fabricate) on substrates of eps_r 4.2-4.6 and
tabulates where it resonates: the lookup from a VNA-measured resonance back to the
board's real eps_r. Each run is Simple_Patch_Antenna.py with --design / --eps-r / --out,
so no plot window opens. Runs already saved in sweep/ are reused (delete one to redo it).

    python sweep_eps_r.py                  # simulate what is missing, write eps_r_sweep.md
    python sweep_eps_r.py --measured 5.86  # also: eps_r for a measured resonance in GHz
"""

import argparse, os, subprocess, sys
import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

DESIGN = 4.4  # the geometry, fixed for every run
EPS_R = [4.2, 4.3, 4.4, 4.5, 4.6]  # the substrates simulated
BAND = (5.75e9, 5.85e9)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "sweep")


def run(eps):
    """One simulation, unless its data is saved already. Its stdout goes to a .log."""
    tag = "d{:.2f}_e{:.2f}".format(DESIGN, eps)
    npz = os.path.join(OUT, tag + ".npz")
    if not os.path.exists(npz):
        os.makedirs(OUT, exist_ok=True)
        print("simulating eps_r {:.2f} (log: sweep/{}.log)".format(eps, tag), flush=True)
        cmd = [
            sys.executable,
            "-u",  # unbuffered, so the log keeps print and openEMS output in order
            os.path.join(HERE, "Simple_Patch_Antenna.py"),
            "--design",
            str(DESIGN),
            "--eps-r",
            str(eps),
            "--out",
            OUT,
        ]
        with open(os.path.join(OUT, tag + ".log"), "w") as log:
            subprocess.run(cmd, stdout=log, stderr=subprocess.STDOUT, check=True)
    d = np.load(npz)
    f, s11 = d["f"], d["s11_dB"]
    i = int(np.argmin(s11))
    lo = hi = i
    while lo > 0 and s11[lo - 1] < -10:
        lo -= 1
    while hi < len(f) - 1 and s11[hi + 1] < -10:
        hi += 1
    in_band = (f >= BAND[0]) & (f <= BAND[1])
    return dict(
        eps=eps,
        f=f,
        s11=s11,
        f_res=f[i],
        s11_min=s11[i],
        band=(f[lo], f[hi]) if s11[i] < -10 else None,
        worst=s11[in_band].max(),
        dmax=float(d["Dmax_dBi"]),
        geometry=d["geometry"],
        h=float(d["h"]),
        tan_d=float(d["tan_d"]),
    )


parser = argparse.ArgumentParser(description="eps_r sweep of the fixed eps_r 4.4 patch")
parser.add_argument("--measured", type=float, help="measured resonance (GHz) -> eps_r")
args = parser.parse_args()

runs = [run(eps) for eps in EPS_R]
# The point of the sweep: one geometry, only the material changes
for r in runs[1:]:
    assert np.allclose(r["geometry"], runs[0]["geometry"]), "geometry differs between runs"

eps = np.array([r["eps"] for r in runs])
f_res = np.array([r["f_res"] for r in runs])
slope, _ = np.polyfit(eps, f_res, 1)  # Hz per unit eps_r
f_design = f_res[np.argmin(np.abs(eps - DESIGN))]

# Combined S11 plot
fig, ax = plt.subplots(figsize=(8, 5), tight_layout=True)
for r in runs:
    ax.plot(r["f"] / 1e9, r["s11"], label="eps_r {:.2f}".format(r["eps"]))
ax.axvspan(BAND[0] / 1e9, BAND[1] / 1e9, color="g", alpha=0.15, label="5.75-5.85 GHz")
ax.axhline(-10, color="k", linestyle=":", linewidth=1)
ax.set_xlim(5.3, 6.3)
ax.set_xlabel("Frequency (GHz)")
ax.set_ylabel("S11 (dB)")
ax.set_title("eps_r {:.1f} geometry on substrates of eps_r 4.2-4.6".format(DESIGN))
ax.grid()
ax.legend()
fig.savefig(os.path.join(HERE, "eps_r_sweep.png"))

# Table
L, W, inset, line = runs[0]["geometry"]
rows = []
for r in runs:
    band = "{:.3f}-{:.3f}".format(*np.divide(r["band"], 1e9)) if r["band"] else "none"
    rows.append(
        "| {:.2f} | {:.3f} | {:.1f} | {} | {:.1f} | {:.1f} |".format(
            r["eps"], r["f_res"] / 1e9, r["s11_min"], band, r["worst"], r["dmax"]
        )
    )
md = """# eps_r sweep, fixed geometry (K8 calibration curve)

Generated by `sweep_eps_r.py`, do not edit by hand. Per-run plots and logs in `sweep/`.

One geometry in every row: the eps_r {design:.2f} design from `results.md` (patch L
{L:.3f} mm, W {W:.3f} mm, inset {inset:.3f} mm, line {line:.3f} mm), on one shared mesh.
Only the substrate's eps_r changes. FR4 dielectric h {h:.3f} mm, tan d {tan_d:.3f}.

| eps_r | S11 min at (GHz) | S11 min (dB) | -10 dB band (GHz) | worst over 5.75-5.85 GHz (dB) | Dmax (dBi) |
|---|---|---|---|---|---|
{rows}

Slope (linear fit): {slope:+.0f} MHz per +0.1 eps_r.

Reading a measurement: `python sweep_eps_r.py --measured <GHz>` interpolates this table
(no new simulation), and prints the guide's formula
`eps_r ~ {design} * (f_sim / f_meas)^2` (f_sim = {f_design:.3f} GHz) as a cross-check.

![S11 vs eps_r](eps_r_sweep.png)
""".format(
    design=DESIGN,
    L=L,
    W=W,
    inset=inset,
    line=line,
    h=runs[0]["h"],
    tan_d=runs[0]["tan_d"],
    rows="\n".join(rows),
    slope=slope * 0.1 / 1e6,
    f_design=f_design / 1e9,
)
with open(os.path.join(HERE, "eps_r_sweep.md"), "w") as fh:
    fh.write(md)
print(md)

if args.measured is not None:
    f_meas = args.measured * 1e9
    order = np.argsort(f_res)  # np.interp wants increasing x; f_res falls as eps_r rises
    if not f_res.min() <= f_meas <= f_res.max():
        print("{:.3f} GHz is outside the swept range: extend EPS_R".format(args.measured))
    else:
        print(
            "measured {:.3f} GHz -> eps_r {:.3f} (table), {:.3f} (formula)".format(
                args.measured,
                np.interp(f_meas, f_res[order], eps[order]),
                DESIGN * (f_design / f_meas) ** 2,
            )
        )
